<?php

// PermissionSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $permissions = [
            'hospital.view',
            'hospital.update',
            'facilities.view',
            'facilities.create',
            'facilities.update',
            'facilities.activate',
            'departments.view',
            'departments.manage',
            'staff.view',
            'staff.invite',
            'staff.update',
            'staff.suspend',
            'staff.assign-facilities',
            'roles.view',
            'roles.assign',
            'permissions.manage',
            'audit.view',
            'audit.export',
            'settings.manage',
            'numbering.manage',
            'website.view',
            'website.edit',
            'website.publish',
            'website.unpublish',
            'website.manage_media',
            'website.manage_navigation',
            'website.manage_seo',
            'website.manage_theme',
            'website.view_revisions',
            'website.restore_revision',
            'patients.view',
            'patients.register',
            'patients.update',
            'patients.archive',
            'patients.record-alerts',
            'patients.view-sensitive',
            'appointments.view',
            'appointments.book',
            'appointments.manage',
            'appointment-requests.review',
            'queues.view',
            'queues.manage',
            'queues.prioritize',
            'admissions.view',
            'admissions.request',
            'admissions.approve',
            'admissions.manage',
            'admissions.discharge',
            'admissions.discharge.override',
            'encounters.view',
            'encounters.manage',
            'encounters.sign',
            'vitals.record',
            'inpatient.view',
            'inpatient.document',
            'inpatient.sign',
            'inpatient.orders',
            'inpatient.handover',
            'inpatient.discharge-summary.sign',
            'billing.catalogue.view',
            'billing.catalogue.manage',
            'invoices.view',
            'invoices.create',
            'invoices.issue',
            'invoices.void',
            'payments.view',
            'payments.post',
            'payments.reverse',
            'refunds.request',
            'refunds.approve',
            'refunds.process',
            'cashier-shifts.open',
            'cashier-shifts.close',
            'cashier-shifts.review',
            'lab.catalogue.view',
            'lab.catalogue.manage',
            'lab.requests.view',
            'lab.requests.order',
            'lab.specimens.manage',
            'lab.results.enter',
            'lab.results.verify',
            'lab.results.approve',
            'lab.results.amend',
            'radiology.catalogue.view',
            'radiology.catalogue.manage',
            'radiology.requests.view',
            'radiology.requests.order',
            'radiology.schedule.manage',
            'radiology.perform',
            'radiology.reports.write',
            'radiology.reports.verify',
            'radiology.reports.approve',
            'radiology.reports.amend',
            'radiology.attachments.manage',
            'inventory.view',
            'inventory.catalogue.manage',
            'inventory.stock.receive',
            'inventory.stock.transfer',
            'inventory.stock.adjust',
            'inventory.adjustments.approve',
            'procurement.view',
            'procurement.suppliers.manage',
            'procurement.requisitions.create',
            'procurement.requisitions.approve',
            'procurement.receive',
            'procurement.reverse',
            'procurement.over-receive',
            'prescriptions.view',
            'prescriptions.create',
            'prescriptions.sign',
            'prescriptions.review',
            'prescriptions.dispense',
            'prescriptions.reverse',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        Role::where('name', 'superadmin')->first()
            ->givePermissionTo(Permission::all());

        $adminPermissions = [
            'hospital.view',
            'hospital.update',
            'facilities.view',
            'facilities.create',
            'facilities.update',
            'facilities.activate',
            'departments.view',
            'departments.manage',
            'staff.view',
            'staff.invite',
            'staff.update',
            'staff.suspend',
            'staff.assign-facilities',
            'roles.view',
            'roles.assign',
            'audit.view',
            'settings.manage',
            'numbering.manage',
            'website.view',
            'website.edit',
            'website.publish',
            'website.unpublish',
            'website.manage_media',
            'website.manage_navigation',
            'website.manage_seo',
            'website.manage_theme',
            'website.view_revisions',
            'website.restore_revision',
            'patients.view',
            'patients.register',
            'patients.update',
            'patients.archive',
            'patients.record-alerts',
            'patients.view-sensitive',
            'appointments.view',
            'appointments.book',
            'appointments.manage',
            'appointment-requests.review',
            'queues.view',
            'queues.manage',
            'queues.prioritize',
            'admissions.view',
            'admissions.request',
            'admissions.approve',
            'admissions.manage',
            'admissions.discharge',
            'admissions.discharge.override',
            'encounters.view',
            'encounters.manage',
            'encounters.sign',
            'vitals.record',
            'inpatient.view',
            'inpatient.document',
            'inpatient.sign',
            'inpatient.orders',
            'inpatient.handover',
            'inpatient.discharge-summary.sign',
            'billing.catalogue.view',
            'billing.catalogue.manage',
            'invoices.view',
            'invoices.create',
            'invoices.issue',
            'invoices.void',
            'payments.view',
            'payments.post',
            'payments.reverse',
            'refunds.request',
            'refunds.approve',
            'refunds.process',
            'cashier-shifts.open',
            'cashier-shifts.close',
            'cashier-shifts.review',
            'lab.catalogue.view',
            'lab.catalogue.manage',
            'lab.requests.view',
            'lab.requests.order',
            'lab.specimens.manage',
            'lab.results.enter',
            'lab.results.verify',
            'lab.results.approve',
            'lab.results.amend',
            'radiology.catalogue.view',
            'radiology.catalogue.manage',
            'radiology.requests.view',
            'radiology.requests.order',
            'radiology.schedule.manage',
            'radiology.perform',
            'radiology.reports.write',
            'radiology.reports.verify',
            'radiology.reports.approve',
            'radiology.reports.amend',
            'radiology.attachments.manage',
            'inventory.view',
            'inventory.catalogue.manage',
            'inventory.stock.receive',
            'inventory.stock.transfer',
            'inventory.stock.adjust',
            'inventory.adjustments.approve',
            'procurement.view',
            'procurement.suppliers.manage',
            'procurement.requisitions.create',
            'procurement.requisitions.approve',
            'procurement.receive',
            'procurement.reverse',
            'procurement.over-receive',
            'prescriptions.view',
            'prescriptions.create',
            'prescriptions.sign',
            'prescriptions.review',
            'prescriptions.dispense',
            'prescriptions.reverse',
        ];

        Role::where('name', 'admin')->first()?->syncPermissions(array_values(array_diff($adminPermissions, [
            'website.publish',
            'website.unpublish',
            'website.restore_revision',
        ])));

        Role::where('name', 'hospital-admin')->first()?->syncPermissions($adminPermissions);

        Role::whereIn('name', [
            'pharmacist',
            'laboratory-scientist',
            'radiology-staff',
            'cashier',
            'accountant',
            'storekeeper',
            'blood-bank-staff',
            'hmo-claims-officer',
        ])->get()->each(fn (Role $role) => $role->syncPermissions([
            'hospital.view',
            'facilities.view',
            'departments.view',
        ]));

        Role::whereIn('name', ['cashier', 'accountant'])->get()->each(fn (Role $role) => $role->syncPermissions([
            'hospital.view',
            'facilities.view',
            'departments.view',
            'patients.view',
            'billing.catalogue.view',
            'invoices.view',
            ...($role->name === 'cashier' ? [
                'payments.view',
                'payments.post',
                'refunds.request',
                'cashier-shifts.open',
                'cashier-shifts.close',
            ] : [
                'billing.catalogue.manage',
                'invoices.create',
                'invoices.issue',
                'invoices.void',
                'payments.view',
                'payments.reverse',
                'refunds.approve',
                'refunds.process',
                'cashier-shifts.review',
            ]),
        ]));

        Role::where('name', 'receptionist')->first()?->syncPermissions([
            'hospital.view',
            'facilities.view',
            'departments.view',
            'patients.view',
            'patients.register',
            'patients.update',
            'patients.record-alerts',
            'patients.view-sensitive',
            'appointments.view',
            'appointments.book',
            'appointment-requests.review',
            'queues.view',
            'queues.manage',
            'encounters.view',
            'vitals.record',
            'billing.catalogue.view',
            'invoices.view',
            'invoices.create',
            'lab.requests.view',
            'lab.requests.order',
            'radiology.requests.view',
            'radiology.requests.order',
        ]);

        Role::whereIn('name', ['doctor', 'nurse'])->get()->each(fn (Role $role) => $role->syncPermissions([
            'hospital.view',
            'facilities.view',
            'departments.view',
            'patients.view',
            'patients.update',
            'patients.record-alerts',
            'patients.view-sensitive',
            'appointments.view',
            'appointments.manage',
            'queues.view',
            'queues.manage',
            'encounters.view',
            'vitals.record',
            'inpatient.view',
            'inpatient.document',
            'inpatient.handover',
            'inpatient.orders',
            ...($role->name === 'doctor' ? ['encounters.manage', 'encounters.sign', 'admissions.approve', 'admissions.manage', 'admissions.discharge.override', 'inpatient.view', 'inpatient.document', 'inpatient.sign', 'inpatient.orders', 'inpatient.handover', 'inpatient.discharge-summary.sign'] : []),
            ...($role->name === 'doctor' ? ['prescriptions.view', 'prescriptions.create', 'prescriptions.sign'] : []),
            'billing.catalogue.view',
            'invoices.view',
            'lab.catalogue.view',
            'lab.requests.view',
            ...($role->name === 'doctor' ? ['lab.requests.order'] : []),
            'radiology.catalogue.view',
            'radiology.requests.view',
            ...($role->name === 'doctor' ? ['radiology.requests.order'] : []),
        ]));

        Role::where('name', 'laboratory-scientist')->first()?->syncPermissions([
            'hospital.view',
            'facilities.view',
            'departments.view',
            'patients.view',
            'encounters.view',
            'billing.catalogue.view',
            'invoices.view',
            'lab.catalogue.view',
            'lab.catalogue.manage',
            'lab.requests.view',
            'lab.requests.order',
            'lab.specimens.manage',
            'lab.results.enter',
            'lab.results.verify',
            'lab.results.approve',
            'lab.results.amend',
        ]);

        Role::where('name', 'radiology-staff')->first()?->syncPermissions([
            'hospital.view',
            'facilities.view',
            'departments.view',
            'patients.view',
            'encounters.view',
            'billing.catalogue.view',
            'invoices.view',
            'radiology.catalogue.view',
            'radiology.catalogue.manage',
            'radiology.requests.view',
            'radiology.requests.order',
            'radiology.schedule.manage',
            'radiology.perform',
            'radiology.reports.write',
            'radiology.reports.verify',
            'radiology.reports.approve',
            'radiology.reports.amend',
            'radiology.attachments.manage',
        ]);

        Role::whereIn('name', ['pharmacist', 'storekeeper'])->get()->each(fn (Role $role) => $role->syncPermissions([
            'hospital.view',
            'facilities.view',
            'departments.view',
            'inventory.view',
            'inventory.catalogue.manage',
            'inventory.stock.receive',
            'inventory.stock.transfer',
            'inventory.stock.adjust',
            ...($role->name === 'pharmacist' ? ['inventory.adjustments.approve'] : []),
            'procurement.view',
            ...($role->name === 'storekeeper' ? ['procurement.suppliers.manage', 'procurement.requisitions.create', 'procurement.receive'] : []),
            ...($role->name === 'pharmacist' ? ['procurement.requisitions.approve', 'procurement.receive', 'procurement.reverse', 'procurement.over-receive'] : []),
            'prescriptions.view',
            ...($role->name === 'pharmacist' ? ['prescriptions.review', 'prescriptions.dispense', 'prescriptions.reverse'] : []),
        ]));

        Role::where('name', 'patient')->first()?->syncPermissions([]);
    }
}
