<script setup>
import ActionToolbar from '@/Components/Admin/ActionToolbar.vue';
import ConfirmDialog from '@/Components/Admin/ConfirmDialog.vue';
import FormModal from '@/Components/Admin/FormModal.vue';
import PageHeader from '@/Components/Admin/PageHeader.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import AppLayout from '@/Layouts/AppLayout.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';

const props = defineProps({ chart: { type: Object, required: true }, timeline: { type: Array, default: () => [] } });
const now = () => new Date().toISOString().slice(0, 16);
const progress = useForm({ note_type: 'soap', subjective: '', objective: '', assessment: '', plan: '', narrative: '' });
const amendment = useForm({ reason: '', content: '' });
const nursing = useForm({ shift: 'day', note: '' });
const observation = useForm({ temperature: '', temperature_unit: 'C', pulse: '', respiratory_rate: '', blood_pressure_systolic: '', blood_pressure_diastolic: '', oxygen_saturation: '', pain_score: '', glucose: '', glucose_unit: 'mmol/L', consciousness_notes: '', observed_at: now() });
const intake = useForm({ direction: 'intake', measurement_type: 'oral fluids', quantity: '', unit: 'ml', notes: '', measured_at: now() });
const carePlan = useForm({ problem: '', goal: '', intervention: '', evaluation: '', status: 'active' });
const order = useForm({ order_type: 'nursing_care', instruction: '', status: 'active' });
const handover = useForm({ from_shift: 'day', to_shift: 'night', summary: '' });
const discharge = useForm({ admission_summary: props.chart.discharge_summary?.admission_summary || props.chart.admission?.reason || '', diagnosis_summary: props.chart.discharge_summary?.diagnosis_summary || props.chart.diagnoses?.map((item) => item.description).join('\n') || '', results_summary: props.chart.discharge_summary?.results_summary || '', clinical_course: props.chart.discharge_summary?.clinical_course || '', discharge_plan: props.chart.discharge_summary?.discharge_plan || '' });
const orderAction = useForm({ action: '', reason: '' });
const blank = useForm({});
const activeModal = ref(null);
const target = ref(null);
function fullName(patient) { return [patient?.first_name, patient?.middle_name, patient?.last_name].filter(Boolean).join(' '); }
function save(form, url, reset = true) { form.post(url, { preserveScroll: true, onSuccess: () => { activeModal.value = null; if (reset) form.reset(); } }); }
function signNote(note) { blank.post(`/admin/inpatient/progress-notes/${note.id}/sign`, { preserveScroll: true }); }
function openAmend(note) { target.value = note; amendment.defaults({ reason: '', content: '' }); amendment.reset(); activeModal.value = 'amendment'; }
function saveAmendment() { save(amendment, `/admin/inpatient/progress-notes/${target.value.id}/amendments`); }
function openOrderAction(item, action) { target.value = item; orderAction.defaults({ action, reason: '' }); orderAction.reset(); activeModal.value = 'order-action'; }
function saveOrderAction() { orderAction.patch(`/admin/inpatient/orders/${target.value.id}`, { preserveScroll: true, onSuccess: () => { activeModal.value = null; orderAction.reset(); } }); }
function signSummary() { blank.post(`/admin/inpatient/discharge-summaries/${props.chart.discharge_summary.id}/sign`, { preserveScroll: true }); }
</script>

<template>
    <Head :title="`Ward Chart - ${fullName(chart.patient)}`" />
    <AppLayout :title="fullName(chart.patient) || 'Ward Chart'">
        <PageHeader :title="fullName(chart.patient) || 'Ward Chart'" :description="`Status: ${chart.status}`">
            <template #actions>
                <ActionToolbar align="end">
                    <Link href="/admin/inpatient" class="rounded-md border px-3 py-2 text-sm font-bold">Back</Link>
                    <PrimaryButton type="button" @click="activeModal = 'progress'">Progress Note</PrimaryButton>
                    <PrimaryButton type="button" @click="activeModal = 'nursing'">Nursing Note</PrimaryButton>
                    <PrimaryButton type="button" @click="activeModal = 'observation'">Observation</PrimaryButton>
                    <PrimaryButton type="button" @click="activeModal = 'intake'">Intake/Output</PrimaryButton>
                    <PrimaryButton type="button" @click="activeModal = 'care'">Care Plan</PrimaryButton>
                    <PrimaryButton type="button" @click="activeModal = 'order'">Order</PrimaryButton>
                    <PrimaryButton type="button" @click="activeModal = 'handover'">Handover</PrimaryButton>
                    <PrimaryButton type="button" @click="activeModal = 'discharge'">Discharge Summary</PrimaryButton>
                </ActionToolbar>
            </template>
        </PageHeader>

        <div class="mb-4 grid gap-3 md:grid-cols-3">
            <section class="rounded-lg border border-slate-200 bg-white p-4 text-sm dark:border-slate-800 dark:bg-slate-900"><p class="font-black">{{ chart.admission?.admission_number }}</p><p class="break-words text-slate-500">{{ chart.ward?.name || chart.admission?.ward?.name }} - {{ chart.bed?.label || chart.admission?.bed?.label }}</p></section>
            <section class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-950"><p class="font-black">Allergies</p><p v-for="item in chart.patient?.allergies || []" :key="item.id" class="break-words">{{ item.substance }} - {{ item.severity }}</p><p v-if="!chart.patient?.allergies?.length">None recorded</p></section>
            <section class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><p class="font-black">Alerts</p><p v-for="item in chart.patient?.alerts || []" :key="item.id" class="break-words">{{ item.title }} - {{ item.severity }}</p><p v-if="!chart.patient?.alerts?.length">None recorded</p></section>
        </div>

        <div class="grid gap-6">
            <section class="min-w-0 rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Progress Notes</h2><article v-for="note in chart.progress_notes" :key="note.id" class="mt-3 min-w-0 border-t pt-3 text-sm"><p class="break-words font-bold">{{ note.note_type }} - {{ note.status }}</p><p class="break-words">{{ note.assessment || note.narrative || note.subjective }}</p><ActionToolbar class="mt-2"><button v-if="note.status === 'draft'" class="rounded-md border px-2 py-1 text-xs font-bold" type="button" @click="signNote(note)">Sign</button><button v-if="note.status === 'signed'" class="rounded-md border px-2 py-1 text-xs font-bold" type="button" @click="openAmend(note)">Amend</button></ActionToolbar><p v-for="amend in note.amendments" :key="amend.id" class="mt-2 break-words text-xs text-slate-500">Amendment: {{ amend.reason }} - {{ amend.content }}</p></article></section>
            <section class="grid gap-6 lg:grid-cols-3">
                <div class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Nursing Notes</h2><p v-for="item in chart.nursing_notes" :key="item.id" class="mt-3 break-words text-sm">{{ item.shift }} - {{ item.note }}</p></div>
                <div class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Observations</h2><p v-for="item in chart.observations" :key="item.id" class="mt-3 break-words text-sm">{{ item.observed_at }} - T {{ item.temperature || '-' }} - BP {{ item.blood_pressure_systolic || '-' }}/{{ item.blood_pressure_diastolic || '-' }}</p></div>
                <div class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Intake / Output</h2><p v-for="item in chart.intake_outputs" :key="item.id" class="mt-3 break-words text-sm">{{ item.direction }} - {{ item.measurement_type }} - {{ item.quantity }} {{ item.unit }}</p></div>
            </section>
            <section class="grid gap-6 lg:grid-cols-3">
                <div class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Care Plans</h2><p v-for="item in chart.care_plans" :key="item.id" class="mt-3 break-words text-sm"><strong>{{ item.problem }}</strong> - {{ item.status }}<br>{{ item.goal }}</p></div>
                <div class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Handovers</h2><p v-for="item in chart.handovers" :key="item.id" class="mt-3 break-words text-sm">{{ item.from_shift }} to {{ item.to_shift }} - {{ item.summary }}</p></div>
                <div class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Timeline</h2><p v-for="item in timeline" :key="`${item.type}-${item.label}-${item.occurred_at}`" class="mt-2 break-words text-sm">{{ item.type }} - {{ item.label }} - {{ item.occurred_at }}</p></div>
            </section>
            <section class="min-w-0 rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Orders</h2><article v-for="item in chart.orders" :key="item.id" class="grid min-w-0 gap-3 border-t py-3 text-sm md:grid-cols-[1fr_auto]"><div><p class="break-words font-bold">{{ item.order_type }} - {{ item.status }}</p><p class="break-words">{{ item.instruction }}</p></div><ActionToolbar align="end"><button class="rounded-md border px-2 py-1 text-xs font-bold" type="button" @click="openOrderAction(item, 'activate')">Activate</button><button class="rounded-md border px-2 py-1 text-xs font-bold" type="button" @click="openOrderAction(item, 'acknowledge')">Acknowledge</button><button class="rounded-md border px-2 py-1 text-xs font-bold" type="button" @click="openOrderAction(item, 'complete')">Complete</button><button class="rounded-md border px-2 py-1 text-xs font-bold" type="button" @click="openOrderAction(item, 'cancel')">Cancel</button></ActionToolbar></article></section>
            <section class="min-w-0 rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-wrap justify-between gap-3"><h2 class="font-black">Discharge Summary</h2><button v-if="chart.discharge_summary?.status === 'draft'" class="rounded-md border px-3 py-2 text-sm font-bold" type="button" @click="signSummary">Sign summary</button></div><p class="mt-3 break-words text-sm">{{ chart.discharge_summary?.discharge_plan || 'No discharge summary drafted.' }}</p></section>
        </div>

        <FormModal :show="activeModal === 'progress'" title="Clinician Progress Note" :form="progress" submit-label="Save note" size="full" @close="activeModal = null" @submit="save(progress, `/admin/inpatient/charts/${chart.id}/progress-notes`)"><div class="grid gap-3"><select v-model="progress.note_type" class="rounded-md border-slate-300"><option value="soap">SOAP</option><option value="ward_round">Ward round</option><option value="review">Review</option><option value="procedure_note">Procedure note</option><option value="other">Other</option></select><textarea v-model="progress.subjective" class="rounded-md border-slate-300" rows="2" placeholder="Subjective"></textarea><textarea v-model="progress.objective" class="rounded-md border-slate-300" rows="2" placeholder="Objective"></textarea><textarea v-model="progress.assessment" class="rounded-md border-slate-300" rows="2" placeholder="Assessment"></textarea><textarea v-model="progress.plan" class="rounded-md border-slate-300" rows="2" placeholder="Plan"></textarea><textarea v-model="progress.narrative" class="rounded-md border-slate-300" rows="3" placeholder="Additional narrative"></textarea></div></FormModal>
        <FormModal :show="activeModal === 'nursing'" title="Nursing Note" :form="nursing" submit-label="Record note" size="full" @close="activeModal = null" @submit="save(nursing, `/admin/inpatient/charts/${chart.id}/nursing-notes`)"><select v-model="nursing.shift" class="w-full rounded-md border-slate-300"><option value="day">Day</option><option value="night">Night</option><option value="evening">Evening</option></select><textarea v-model="nursing.note" class="mt-3 w-full rounded-md border-slate-300" rows="6" placeholder="Nursing note"></textarea></FormModal>
        <FormModal :show="activeModal === 'observation'" title="Observation Chart" :form="observation" submit-label="Record observation" size="full" @close="activeModal = null" @submit="save(observation, `/admin/inpatient/charts/${chart.id}/observations`)"><div class="grid gap-3 sm:grid-cols-2"><TextInput id="obs_temp" v-model="observation.temperature" label="Temperature" type="number" step="0.1" /><select v-model="observation.temperature_unit" class="rounded-md border-slate-300"><option value="C">C</option><option value="F">F</option></select><TextInput id="obs_pulse" v-model="observation.pulse" label="Pulse" type="number" /><TextInput id="obs_resp" v-model="observation.respiratory_rate" label="Respiration" type="number" /><TextInput id="obs_bp_s" v-model="observation.blood_pressure_systolic" label="BP systolic" type="number" /><TextInput id="obs_bp_d" v-model="observation.blood_pressure_diastolic" label="BP diastolic" type="number" /><TextInput id="obs_spo2" v-model="observation.oxygen_saturation" label="Oxygen" type="number" /><TextInput id="obs_pain" v-model="observation.pain_score" label="Pain" type="number" /><TextInput id="obs_glucose" v-model="observation.glucose" label="Glucose" type="number" step="0.1" /><TextInput id="obs_time" v-model="observation.observed_at" label="Observed at" type="datetime-local" /></div><textarea v-model="observation.consciousness_notes" class="mt-3 w-full rounded-md border-slate-300" rows="2" placeholder="Consciousness notes"></textarea></FormModal>
        <FormModal :show="activeModal === 'intake'" title="Intake / Output" :form="intake" submit-label="Record intake/output" @close="activeModal = null" @submit="save(intake, `/admin/inpatient/charts/${chart.id}/intake-output`)"><div class="grid gap-3 sm:grid-cols-2"><select v-model="intake.direction" class="rounded-md border-slate-300"><option value="intake">Intake</option><option value="output">Output</option></select><TextInput id="io_type" v-model="intake.measurement_type" label="Type" /><TextInput id="io_qty" v-model="intake.quantity" label="Quantity" type="number" step="0.01" /><TextInput id="io_unit" v-model="intake.unit" label="Unit" /><TextInput id="io_time" v-model="intake.measured_at" label="Measured at" type="datetime-local" /></div><textarea v-model="intake.notes" class="mt-3 w-full rounded-md border-slate-300" rows="2" placeholder="Notes"></textarea></FormModal>
        <FormModal :show="activeModal === 'care'" title="Care Plan" :form="carePlan" submit-label="Record care plan" size="full" @close="activeModal = null" @submit="save(carePlan, `/admin/inpatient/charts/${chart.id}/care-plans`)"><div class="grid gap-3"><textarea v-model="carePlan.problem" class="rounded-md border-slate-300" rows="2" placeholder="Problem"></textarea><textarea v-model="carePlan.goal" class="rounded-md border-slate-300" rows="2" placeholder="Goal"></textarea><textarea v-model="carePlan.intervention" class="rounded-md border-slate-300" rows="2" placeholder="Intervention"></textarea><textarea v-model="carePlan.evaluation" class="rounded-md border-slate-300" rows="2" placeholder="Evaluation"></textarea></div></FormModal>
        <FormModal :show="activeModal === 'order'" title="Clinician Order" :form="order" submit-label="Record order" @close="activeModal = null" @submit="save(order, `/admin/inpatient/charts/${chart.id}/orders`)"><div class="grid gap-3"><select v-model="order.order_type" class="rounded-md border-slate-300"><option value="nursing_care">Nursing care</option><option value="monitoring">Monitoring</option><option value="diet">Diet</option><option value="activity">Activity</option><option value="investigation">Investigation</option></select><textarea v-model="order.instruction" class="rounded-md border-slate-300" rows="3" placeholder="Order instruction"></textarea><select v-model="order.status" class="rounded-md border-slate-300"><option value="draft">Draft</option><option value="active">Active</option></select></div></FormModal>
        <FormModal :show="activeModal === 'handover'" title="Shift Handover" :form="handover" submit-label="Sign handover" size="full" @close="activeModal = null" @submit="save(handover, `/admin/inpatient/charts/${chart.id}/handovers`)"><div class="grid gap-3 sm:grid-cols-2"><TextInput id="from_shift" v-model="handover.from_shift" label="From shift" /><TextInput id="to_shift" v-model="handover.to_shift" label="To shift" /></div><textarea v-model="handover.summary" class="mt-3 w-full rounded-md border-slate-300" rows="6" placeholder="Handover summary"></textarea></FormModal>
        <FormModal :show="activeModal === 'discharge'" title="Discharge Summary" :form="discharge" submit-label="Draft summary" size="full" @close="activeModal = null" @submit="save(discharge, `/admin/inpatient/charts/${chart.id}/discharge-summary`, false)"><div class="grid gap-3"><textarea v-model="discharge.admission_summary" class="rounded-md border-slate-300" rows="2" placeholder="Admission summary"></textarea><textarea v-model="discharge.diagnosis_summary" class="rounded-md border-slate-300" rows="2" placeholder="Diagnosis summary"></textarea><textarea v-model="discharge.results_summary" class="rounded-md border-slate-300" rows="2" placeholder="Results summary"></textarea><textarea v-model="discharge.clinical_course" class="rounded-md border-slate-300" rows="2" placeholder="Clinical course"></textarea><textarea v-model="discharge.discharge_plan" class="rounded-md border-slate-300" rows="2" placeholder="Discharge plan"></textarea></div></FormModal>
        <FormModal :show="activeModal === 'amendment'" title="Progress Note Amendment" :form="amendment" submit-label="Add amendment" @close="activeModal = null" @submit="saveAmendment"><div class="grid gap-3"><input v-model="amendment.reason" class="rounded-md border-slate-300" placeholder="Amendment reason"><textarea v-model="amendment.content" class="rounded-md border-slate-300" rows="3" placeholder="Amendment content"></textarea></div></FormModal>
        <ConfirmDialog :show="activeModal === 'order-action'" :title="`${orderAction.action} order`" confirm-label="Save action" :form="orderAction" :require-reason="['cancel', 'discontinue'].includes(orderAction.action)" @close="activeModal = null" @confirm="saveOrderAction" />
    </AppLayout>
</template>
