<script setup>
import ActionToolbar from '@/Components/Admin/ActionToolbar.vue';
import FormModal from '@/Components/Admin/FormModal.vue';
import PageHeader from '@/Components/Admin/PageHeader.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import AppLayout from '@/Layouts/AppLayout.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';

const props = defineProps({ chart: { type: Object, required: true }, doses: { type: Array, default: () => [] } });
const now = () => new Date().toISOString().slice(0, 16);
const form = useForm({ outcome: 'administered', actual_at: now(), quantity_administered: 1, prescription_dispense_id: '', confirmation: { patient: true, medication: true, dose: true, route: true, timing: true }, reason: '', prn_indication: '', prn_response: '' });
const amendment = useForm({ reason: '', content: '' });
const activeModal = ref(null);
const target = ref(null);
function fullName(patient) { return [patient?.first_name, patient?.middle_name, patient?.last_name].filter(Boolean).join(' '); }
function openAdmin(dose) { target.value = dose; form.defaults({ outcome: 'administered', actual_at: now(), quantity_administered: 1, prescription_dispense_id: dose.prescription_item?.dispenses?.find((dispense) => dispense.action === 'dispense')?.id || '', confirmation: { patient: true, medication: true, dose: true, route: true, timing: true }, reason: '', prn_indication: '', prn_response: '' }); form.reset(); activeModal.value = 'admin'; }
function saveAdmin() { form.post(`/admin/emar/schedules/${target.value.id}/administer`, { preserveScroll: true, onSuccess: () => { activeModal.value = null; form.reset(); } }); }
function openAmend(admin) { target.value = admin; amendment.defaults({ reason: '', content: '' }); amendment.reset(); activeModal.value = 'amend'; }
function saveAmend() { amendment.post(`/admin/emar/administrations/${target.value.id}/amendments`, { preserveScroll: true, onSuccess: () => { activeModal.value = null; amendment.reset(); } }); }
</script>

<template>
    <Head :title="`eMAR - ${fullName(chart.patient)}`" />
    <AppLayout :title="`eMAR - ${fullName(chart.patient)}`">
        <PageHeader :title="`eMAR - ${fullName(chart.patient)}`" description="Medication schedule, administration recording and correction history."><template #actions><ActionToolbar align="end"><Link href="/admin/emar" class="rounded-md border px-3 py-2 text-sm font-bold">Back</Link><button class="rounded-md border px-3 py-2 text-sm font-bold" type="button" @click="router.post(`/admin/emar/charts/${chart.id}/sync`, {}, { preserveScroll: true })">Refresh schedule</button></ActionToolbar></template></PageHeader>
        <div class="mb-4 grid gap-3 md:grid-cols-3"><section class="rounded-lg border border-slate-200 bg-white p-4 text-sm dark:border-slate-800 dark:bg-slate-900"><p class="font-black">{{ chart.admission?.admission_number }}</p><p class="break-words text-slate-500">{{ chart.admission?.ward?.name }} - {{ chart.admission?.bed?.label }}</p></section><section class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-950"><p class="font-black">Allergies</p><p v-for="item in chart.patient?.allergies || []" :key="item.id" class="break-words">{{ item.substance }} - {{ item.severity }}</p><p v-if="!chart.patient?.allergies?.length">None recorded</p></section><section class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><p class="font-black">Alerts / Warnings</p><p v-for="item in chart.patient?.alerts || []" :key="item.id" class="break-words">{{ item.title }} - {{ item.severity }}</p><p v-if="!chart.patient?.alerts?.length">No patient alerts recorded</p></section></div>
        <div class="grid gap-6"><section class="min-w-0 rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Medication Schedule</h2><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800"><article v-for="dose in doses" :key="dose.id" class="grid min-w-0 gap-3 py-4 lg:grid-cols-[1fr_auto]"><div class="min-w-0"><p class="break-words font-bold">{{ dose.medicine_name }} - {{ dose.dose }} - {{ dose.route || 'Route not specified' }}</p><p class="break-words text-sm text-slate-500">{{ dose.order_type }} - {{ dose.scheduled_at || 'PRN' }} - {{ dose.due_state }} - {{ dose.status }}</p><p v-if="dose.prn_instructions" class="break-words text-xs text-slate-500">PRN: {{ dose.prn_instructions }}</p><p v-if="dose.prescription_item?.prescription?.status === 'discontinued'" class="text-xs font-bold text-red-700">Prescription discontinued</p></div><PrimaryButton v-if="!dose.administration" type="button" @click="openAdmin(dose)">Record</PrimaryButton><span v-else class="text-sm font-bold text-emerald-700">{{ dose.administration.outcome }}</span></article></div></section><section class="min-w-0 rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-black">Medication History</h2><div class="mt-4 divide-y divide-slate-100 text-sm dark:divide-slate-800"><article v-for="admin in chart.emar_administrations" :key="admin.id" class="grid min-w-0 gap-3 py-3 md:grid-cols-[1fr_auto]"><div><p class="break-words font-bold">{{ admin.medicine_name }} - {{ admin.outcome }}</p><p class="break-words text-slate-500">{{ admin.actual_at }} - Batch {{ admin.batch?.batch_number || 'not consumed' }}</p><p v-for="item in admin.amendments" :key="item.id" class="mt-2 break-words text-xs text-slate-500">Correction: {{ item.reason }} - {{ item.content }}</p></div><button class="rounded-md border px-2 py-1 text-xs font-bold" type="button" @click="openAmend(admin)">Add correction</button></article></div></section></div>
        <FormModal :show="activeModal === 'admin'" title="Medication Administration" :form="form" submit-label="Record administration" size="full" @close="activeModal = null" @submit="saveAdmin"><div class="grid gap-3 md:grid-cols-2"><select v-model="form.outcome" class="rounded-md border-slate-300"><option value="administered">Administered</option><option value="omitted">Omitted</option><option value="refused">Refused</option><option value="held">Held</option><option value="unavailable">Unavailable</option><option value="delayed">Delayed</option><option value="not-given">Not given</option></select><TextInput id="emar_actual_at" v-model="form.actual_at" label="Actual time" type="datetime-local" /><TextInput id="emar_quantity" v-model="form.quantity_administered" label="Quantity administered" type="number" step="0.0001" /><textarea v-model="form.reason" class="rounded-md border-slate-300 md:col-span-2" rows="2" placeholder="Reason for non-administered or delayed outcome"></textarea><textarea v-model="form.prn_indication" class="rounded-md border-slate-300" rows="2" placeholder="PRN indication"></textarea><textarea v-model="form.prn_response" class="rounded-md border-slate-300" rows="2" placeholder="PRN response/effect"></textarea><label v-for="(_, key) in form.confirmation" :key="key" class="text-sm"><input v-model="form.confirmation[key]" type="checkbox"> Confirm {{ key }}</label></div></FormModal>
        <FormModal :show="activeModal === 'amend'" title="Administration Correction" :form="amendment" submit-label="Add correction" @close="activeModal = null" @submit="saveAmend"><div class="grid gap-3"><input v-model="amendment.reason" class="rounded-md border-slate-300" placeholder="Correction reason"><textarea v-model="amendment.content" class="rounded-md border-slate-300" rows="3" placeholder="Correction note"></textarea></div></FormModal>
    </AppLayout>
</template>
